
eureka:
  client:
    serviceUrl:
      defaultZone:  http://admin:admin@localhost:8761/eureka

spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway, true
      routes:
        - id: reservas
          uri: lb://reservations-microservice
          predicates:
            - Path=/reservas/**
          filters:
            - RewritePath=/reservas/(?<segment>.*), /$\{segment}
        - id: hoteles
          uri: lb://hotels-microservice
          predicates:
            - Path=/hoteles/**
          filters:
            - RewritePath=/hoteles/(?<segment>.*), /$\{segment}
        - id: vuelos
          uri: lb://flights-microservice
          predicates:
            - Path=/vuelos/**
          filters:
            - RewritePath=/vuelos/(?<segment>.*), /$\{segment}
server:
  port: 8087


